spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sulaynd/cloud-config-server.git
          default-label: main

#      loadbalancer:
#        ribbon:
#          enabled: false


server:
  port: 9196

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoint:
    shutdown:
      enabled: true #kill process from this trampoline UI
  endpoints:
    web:
      exposure:
        include:
          - '*' #enable all the endpoints